require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - config/initializers/**/*
    - node_modules/**/*
    - bin/**/*
    - db/**/*.rb

Style/Documentation:
  Enabled: false
Rails/FilePath:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
